### ISSUE TITLE
确定项目README.md文档和项目wiki的内容

### ISSUE THREAD

**Issue by neilwangweili** [highsoft-shanghai/hare#34]
**DOD**:
产出一个项目文档规则

**Comment by neilwangweili** [comment]
https://github.com/spring-projects/spring-boot

**Comment by neilwangweili** [comment]
Duplicate issue : https://github.com/highsoft-shanghai/hare/issues/32

**Comment by neilwangweili** [comment]
https://docs.spring.io/spring-boot/docs/3.0.6/reference/htmlsingle/#legal

**Comment by raymond-liao** [comment]
README：
1. 项目介绍（为了什么）
2. quick start
3. Getting Help
4. Reporting Issues
5. Core Features
6. License

**Comment by raymond-liao** [comment]
WiKi 参考 https://docs.spring.io/spring-boot/docs/3.0.6/reference/htmlsingle/ 完成，需要部署到 Hare 官网
