### ISSUE TITLE
从其他项目将已有的能力迁移到该项目

### ISSUE THREAD

**Issue by raymond-liao** [highsoft-shanghai/hare#5]
1. 从 lockers 项目迁移 IAM（登录、注册、权限管理、用户管理）

**Comment by coder-zjz** [comment]
- iam

**Comment by raymond-liao** [comment]
> - iam

👍

**Comment by raymond-liao** [comment]
@neilwangweili 应该有获取 authorities 的 API 吧？要不然怎么知道创建 Roles 的时候 authorities 可以填哪些值

**Comment by neilwangweili** [comment]
有Bug卡，可考虑先Close
